name: Release

on:
  release:
    types:
      - released

jobs:
  release:
    uses: MrThearMan/CI/.github/workflows/release.yml@v0.4.16
    with:
      python-version: "3.11"
      os: "windows-latest"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
